### ISSUE TITLE
Milestone: useful for general audience

### ISSUE THREAD

**Issue by egorlaufer** [egorlaufer/nvim-config#39]
- [x] Repo has LICENSE
- [ ] Repo has README
    - [ ] README states what's included
        - [ ] mini
        - [ ] nfnl
        - [ ] oil
        - [ ] conjure
        - [ ] leap
        - [ ] treesitter
        - [ ] blink.cmp
        - [ ] conform
        - [ ] telescope
        - [ ] vim-commentary
        - [ ] guess-indent
        - [ ] nvim-dap
        - [ ] nvim-dap-ui
        - [ ] vague
        - [ ] nui
        - [ ] plenary
        - [ ] todo-comments
        - [ ] cheatsheet
        - [ ] smear-cursor
        - [ ] nvim-surround
        - [ ] dadbod
        - [ ] nvim-lspconfig
        - [ ] lsp-lines
        - [ ] easydotnet
        - [ ] roslyn.nvim
        - [ ] rzls.nvim
    - [ ] README states how the repo is laid out
    - [ ] README states how to extend this config
- [ ] `init.lua`
    - [ ] Prerequisites listed clearly in README
    - [ ] First launch just works out of the box
- [x] `plugin.fnl` and `plugin/` can be less confusing
- [ ] Split by area instead of by plugin for `plugin/` modules
